# coding: utf-8

"""
    whylogs container API

    Container that hosts the java version of whylogs behind a REST interface.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import whylogs_container_client
from whylogs_container_client.api.whylogs_api import WhylogsApi  # noqa: E501
from whylogs_container_client.rest import ApiException


class TestWhylogsApi(unittest.TestCase):
    """WhylogsApi unit test stubs"""

    def setUp(self):
        self.api = WhylogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_track(self):
        """Test case for track

        Log Data  # noqa: E501
        """
        pass

    def test_track_pub_sub_message(self):
        """Test case for track_pub_sub_message

        Track pub/sub messages  # noqa: E501
        """
        pass

    def test_write_profiles(self):
        """Test case for write_profiles

        Write Profiles  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
