# coding: utf-8

"""
    whylogs container API

    Container that hosts the java version of whylogs behind a REST interface.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.multi_log import MultiLog  # noqa: E501
from swagger_client.rest import ApiException


class TestMultiLog(unittest.TestCase):
    """MultiLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiLog(self):
        """Test MultiLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.multi_log.MultiLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
