# coding: utf-8

"""
    whylogs container API

    Container that hosts the java version of whylogs behind a REST interface.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import whylogs_container_client
from whylogs_container_client.models.log_request import LogRequest  # noqa: E501
from whylogs_container_client.rest import ApiException


class TestLogRequest(unittest.TestCase):
    """LogRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogRequest(self):
        """Test LogRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = whylogs_container_client.models.log_request.LogRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
