# coding: utf-8

"""
    whylogs container API

    Container that hosts the java version of whylogs behind a REST interface.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import whylogs_container_client
from whylogs_container_client.api.debug_api import DebugApi  # noqa: E501
from whylogs_container_client.rest import ApiException


class TestDebugApi(unittest.TestCase):
    """DebugApi unit test stubs"""

    def setUp(self):
        self.api = DebugApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_health(self):
        """Test case for health

        Tell if the http server is healthy.  # noqa: E501
        """
        pass

    def test_log_debug_info(self):
        """Test case for log_debug_info

        Log Debug Info  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
