# coding: utf-8

"""
    whylogs container API

    Container that hosts the java version of whylogs behind a REST interface.  # noqa: E501

    OpenAPI spec version: 1.0

    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from setuptools import setup, find_packages  # noqa: H301

print(find_packages())

NAME = "whylogs-container-client"
VERSION = "0.0.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="whylogs container API",
    author_email="anthony@whylabs.ai",
    url="",
    keywords=["swagger", "whylogs", "container", "client"],
    install_requires=REQUIRES,
    package_dir = {"": "src"},
    packages=find_packages(where="src"),
    include_package_data=True,
    long_description="""\
    Container that hosts the java version of whylogs behind a REST interface.  # noqa: E501
    """
)
