# coding: utf-8

"""
    whylogs container API

    Container that hosts the java version of whylogs behind a REST interface.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WriteProfilesResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'profiles_written': 'int',
        'profile_paths': 'list[str]'
    }

    attribute_map = {
        'profiles_written': 'profilesWritten',
        'profile_paths': 'profilePaths'
    }

    def __init__(self, profiles_written=None, profile_paths=None):  # noqa: E501
        """WriteProfilesResponse - a model defined in Swagger"""  # noqa: E501
        self._profiles_written = None
        self._profile_paths = None
        self.discriminator = None
        self.profiles_written = profiles_written
        self.profile_paths = profile_paths

    @property
    def profiles_written(self):
        """Gets the profiles_written of this WriteProfilesResponse.  # noqa: E501

        The amount of profiles that were written out.  # noqa: E501

        :return: The profiles_written of this WriteProfilesResponse.  # noqa: E501
        :rtype: int
        """
        return self._profiles_written

    @profiles_written.setter
    def profiles_written(self, profiles_written):
        """Sets the profiles_written of this WriteProfilesResponse.

        The amount of profiles that were written out.  # noqa: E501

        :param profiles_written: The profiles_written of this WriteProfilesResponse.  # noqa: E501
        :type: int
        """
        if profiles_written is None:
            raise ValueError("Invalid value for `profiles_written`, must not be `None`")  # noqa: E501

        self._profiles_written = profiles_written

    @property
    def profile_paths(self):
        """Gets the profile_paths of this WriteProfilesResponse.  # noqa: E501

        The paths of the profiles that were written if they exist. Some writers may not write profiles to anyplace that can be described as a path.  # noqa: E501

        :return: The profile_paths of this WriteProfilesResponse.  # noqa: E501
        :rtype: list[str]
        """
        return self._profile_paths

    @profile_paths.setter
    def profile_paths(self, profile_paths):
        """Sets the profile_paths of this WriteProfilesResponse.

        The paths of the profiles that were written if they exist. Some writers may not write profiles to anyplace that can be described as a path.  # noqa: E501

        :param profile_paths: The profile_paths of this WriteProfilesResponse.  # noqa: E501
        :type: list[str]
        """
        if profile_paths is None:
            raise ValueError("Invalid value for `profile_paths`, must not be `None`")  # noqa: E501

        self._profile_paths = profile_paths

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WriteProfilesResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WriteProfilesResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
